print("Hello there! What is your name?")
name = input()
print("Nice to meet with you " + name)
print('How old are you?')
age = input()
birth_year = 2021 - int(age)
answer = str(birth_year)
print("You were born in "+answer)
